"""Repository rule that auto-detects GCC/MinGW and exports toolchain info."""

_GCC_INFO_BZL = """\
# Auto-generated by gcc_toolchain_repo. Do not edit.
GCC_VERSION = "{version}"
GCC_TARGET = "{target}"
MINGW_ROOT = "{mingw_root}"

TOOL_PATHS = [
{tool_paths}
]

INCLUDE_DIRS = [
{include_dirs}
]
"""

_BUILD = """\
# Auto-generated by gcc_toolchain_repo.
exports_files(["compiler_wrapper.exe"])
"""

# Small C program that translates MSVC-style compiler flags to GCC equivalents.
# Uses GetCommandLineA() + CreateProcessA() to preserve original quoting intact
# (e.g. -DCURL_OS=\"windows\" keeps its embedded quotes).
# __REAL_COMPILER__ is replaced with the actual g++ path at generation time.
_WRAPPER_C = """\
#include <windows.h>
#include <stdio.h>
#include <string.h>
static void sr(char *s,const char *f,const char *t){
    size_t fl=strlen(f),tl=strlen(t);char *p=s;
    while((p=strstr(p,f))!=NULL){
        if(tl!=fl)memmove(p+tl,p+fl,strlen(p+fl)+1);
        memcpy(p,t,tl);p+=tl;}}
static void sp(char *s,const char *pre){
    size_t pl=strlen(pre);char *p=s;
    while((p=strstr(p,pre))!=NULL){
        char *e=p+pl;while(*e&&*e!=' ')e++;
        memmove(p+1,e,strlen(e)+1);}}
static const char *drop[]={
    " /EHsc "," /EHs "," /EHa "," /nologo ",
    " /MDd "," /MTd "," /MD "," /MT ",
    " /Zi "," /Z7 "," /FS "," /bigobj "," /utf-8 ",
    " /GR "," /GR- "," /GL ",
    " /W0 "," /W1 "," /W2 "," /W3 "," /W4 "," /WX "," /WX- ",
    " /O1 "," /O2 "," /Od "," /Ox "," /Oi "," /Os "," /Ot ",
    " /Gy "," /Gw "," /Gd "," /Gr "," /Gz ",
    " /sdl "," /RTC1 "," /FC ",NULL};
static void pp(char *cmd){
    char *p=cmd;
    while((p=strstr(p," @"))!=NULL){
        char fn[4096];char *s=p+2,*e=s;
        while(*e&&*e!=' ')e++;
        int n=(int)(e-s);
        if(n<=0||n>=(int)sizeof(fn)){p=e;continue;}
        memcpy(fn,s,n);fn[n]='\\0';
        FILE *fi=fopen(fn,"r");
        if(!fi){p=e;continue;}
        static char ob[262144];int ol=0;char ln[8192];
        while(fgets(ln,sizeof(ln),fi)){
            int l=(int)strlen(ln);
            while(l>0&&(ln[l-1]=='\\n'||ln[l-1]=='\\r'))ln[--l]='\\0';
            if(!l)continue;
            if(ln[0]=='/'&&(ln[1]=='D'||ln[1]=='I')){ln[0]='-';}
            else if(strncmp(ln,"/FI",3)==0){
                char t[8192];snprintf(t,sizeof(t),"-include %s",ln+3);strcpy(ln,t);}
            else if(strncmp(ln,"/std:",5)==0){
                char t[8192];snprintf(t,sizeof(t),"-std=%s",ln+5);strcpy(ln,t);}
            else if(strncmp(ln,"-DEFAULTLIB:",12)==0||strncmp(ln,"/DEFAULTLIB:",12)==0){
                char *nm=ln+12;int nl=(int)strlen(nm);
                if(nl>4&&strcmp(nm+nl-4,".lib")==0)nl-=4;
                char t[256];snprintf(t,sizeof(t),"-l%.*s",nl,nm);strcpy(ln,t);}
            else if(strcmp(ln,"/EHsc")==0||strcmp(ln,"/EHs")==0||strcmp(ln,"/EHa")==0||
                strcmp(ln,"/nologo")==0||strcmp(ln,"/MD")==0||strcmp(ln,"/MDd")==0||
                strcmp(ln,"/MT")==0||strcmp(ln,"/MTd")==0||strcmp(ln,"/Zi")==0||
                strcmp(ln,"/Z7")==0||strcmp(ln,"/FS")==0||strcmp(ln,"/bigobj")==0||
                strcmp(ln,"/utf-8")==0||strcmp(ln,"/GR")==0||strcmp(ln,"/GR-")==0||
                strcmp(ln,"/GL")==0||strcmp(ln,"/sdl")==0||strcmp(ln,"/RTC1")==0||
                strcmp(ln,"/FC")==0||strcmp(ln,"/Gy")==0||strcmp(ln,"/Gw")==0||
                (ln[0]=='/'&&ln[1]=='W')||(ln[0]=='/'&&ln[1]=='O')||
                strncmp(ln,"/Zc:",4)==0||strncmp(ln,"/wd",3)==0||
                strncmp(ln,"/guard:",7)==0||
                strcmp(ln,"/Gd")==0||strcmp(ln,"/Gr")==0||strcmp(ln,"/Gz")==0)
                continue;
            ol+=snprintf(ob+ol,sizeof(ob)-ol,"%s\\n",ln);
        }
        fclose(fi);
        fi=fopen(fn,"w");
        if(fi){fwrite(ob,1,ol,fi);fclose(fi);}
        p=e;
    }}
int main(void){
    char *raw=GetCommandLineA(),*a=raw;
    if(*a=='"'){a++;while(*a&&*a!='"')a++;if(*a)a++;}
    else while(*a&&*a!=' ')a++;
    while(*a==' ')a++;
    static char c[65536];const char **f;
    int n=snprintf(c,sizeof(c),"\\"__REAL_COMPILER__\\" %s ",a);
    if(n<0||(size_t)n>=sizeof(c))return 1;
    sr(c," /D"," -D");sr(c," /I"," -I");sr(c," /std:"," -std=");sr(c," /FI"," -include ");
    for(f=drop;*f;f++)sr(c,*f," ");
    sp(c," /wd");sp(c," /Zc:");sp(c," /guard:");
    pp(c);
    {STARTUPINFOA si;PROCESS_INFORMATION pi;
    memset(&si,0,sizeof(si));si.cb=sizeof(si);
    si.hStdInput=GetStdHandle(STD_INPUT_HANDLE);
    si.hStdOutput=GetStdHandle(STD_OUTPUT_HANDLE);
    si.hStdError=GetStdHandle(STD_ERROR_HANDLE);
    si.dwFlags=STARTF_USESTDHANDLES;
    if(!CreateProcessA(NULL,c,NULL,NULL,TRUE,0,NULL,NULL,&si,&pi))return 1;
    WaitForSingleObject(pi.hProcess,INFINITE);
    {DWORD ec=1;GetExitCodeProcess(pi.hProcess,&ec);
    CloseHandle(pi.hProcess);CloseHandle(pi.hThread);
    return(int)ec;}}
}
"""

def _try_gcc(rctx, path):
    """Check whether path points to a working GCC and return it, or None."""
    p = rctx.path(path)
    if not p.exists:
        return None
    res = rctx.execute([str(p), "-dumpversion"])
    if res.return_code != 0:
        return None
    return str(p).replace("\\", "/")

# MinGW environments to probe (in order of preference).
_MINGW_ENVS = ["mingw64", "ucrt64", "mingw32"]

def _gcc_toolchain_repo_impl(rctx):
    # --- Locate GCC executable ---
    # Priority: explicit gcc_path > explicit mingw_root > PATH > BAZEL_SH
    gcc = None

    # 1. Explicit gcc_path
    if rctx.attr.gcc_path:
        gcc = _try_gcc(rctx, rctx.attr.gcc_path)
        if not gcc:
            fail("gcc_path '{}' does not point to a working GCC.".format(
                rctx.attr.gcc_path,
            ))

    # 2. Explicit mingw_root (e.g. "D:/env/msys2/mingw64")
    if not gcc and rctx.attr.mingw_root:
        root = rctx.attr.mingw_root.replace("\\", "/").rstrip("/")
        gcc = _try_gcc(rctx, root + "/bin/gcc.exe")
        if not gcc:
            fail("mingw_root '{}' does not contain bin/gcc.exe.".format(
                rctx.attr.mingw_root,
            ))

    # 3. Search PATH
    if not gcc:
        found = rctx.which("gcc")
        if found:
            gcc = _try_gcc(rctx, str(found))

    # 4. Derive from BAZEL_SH  (e.g. D:/env/msys2/usr/bin/bash.exe)
    if not gcc:
        bazel_sh = rctx.os.environ.get("BAZEL_SH", "")
        if bazel_sh:
            sh = bazel_sh.replace("\\", "/")

            # bash.exe is at <msys2_root>/usr/bin/bash.exe
            idx = sh.rfind("/usr/bin/")
            if idx > 0:
                msys2_root = sh[:idx]
                for env in _MINGW_ENVS:
                    gcc = _try_gcc(rctx, msys2_root + "/" + env + "/bin/gcc.exe")
                    if gcc:
                        break

    if not gcc:
        fail(
            "GCC not found. Tried (in order):\n" +
            "  1. gcc_path attribute          (not set)\n" +
            "  2. mingw_root attribute         (not set)\n" +
            "  3. 'gcc' in PATH               (not found)\n" +
            "  4. BAZEL_SH → MSYS2/mingw*/bin (not found)\n" +
            "Set one of: gcc_path, mingw_root, or add MinGW/bin to PATH.",
        )

    # --- Detect version ---
    res = rctx.execute([gcc, "-dumpversion"])
    if res.return_code != 0:
        fail("Cannot run GCC at {}: {}".format(gcc, res.stderr))
    version = res.stdout.strip()

    # --- Detect target triple ---
    res = rctx.execute([gcc, "-dumpmachine"])
    if res.return_code != 0:
        fail("Cannot detect GCC target: " + res.stderr)
    target = res.stdout.strip()

    if "mingw" not in target:
        fail(
            "Expected MinGW GCC (x86_64-w64-mingw32) but found target '{}'.\n".format(target) +
            "Make sure MinGW GCC is in PATH before MSYS GCC.",
        )

    # --- Determine MinGW root directory ---
    bin_idx = gcc.rfind("/bin/")
    if bin_idx < 0:
        fail("Cannot determine MinGW root from GCC path: " + gcc)
    mingw_root = gcc[:bin_idx]

    # --- Build compiler wrapper that translates MSVC flags ---
    gxx = mingw_root + "/bin/g++.exe"
    wrapper_src = _WRAPPER_C.replace("__REAL_COMPILER__", gxx)
    rctx.file("compiler_wrapper.c", wrapper_src)
    res = rctx.execute([gcc, "-O2", "-o", "compiler_wrapper.exe", "compiler_wrapper.c"])
    if res.return_code != 0:
        fail("Failed to compile compiler wrapper:\n" + res.stderr)
    wrapper_path = str(rctx.path("compiler_wrapper.exe")).replace("\\", "/")

    # --- Compute tool paths ---
    tools = [
        ("ar", mingw_root + "/bin/ar.exe"),
        ("cpp", mingw_root + "/bin/cpp.exe"),
        ("gcc", wrapper_path),
        ("gcov", mingw_root + "/bin/gcov.exe"),
        ("ld", mingw_root + "/bin/ld.exe"),
        ("nm", mingw_root + "/bin/nm.exe"),
        ("objdump", mingw_root + "/bin/objdump.exe"),
        ("strip", mingw_root + "/bin/strip.exe"),
    ]
    tool_lines = [
        '    ("{}", "{}"),'.format(name, path)
        for name, path in tools
    ]

    # --- Compute built-in include directories ---
    include_dirs = [
        mingw_root + "/include/c++/" + version,
        mingw_root + "/include/c++/" + version + "/" + target,
        mingw_root + "/include/c++/" + version + "/backward",
        mingw_root + "/lib/gcc/" + target + "/" + version + "/include",
        mingw_root + "/include",
        mingw_root + "/lib/gcc/" + target + "/" + version + "/include-fixed",
        mingw_root + "/" + target + "/include",
    ]
    include_lines = ['    "{}",'.format(d) for d in include_dirs]

    # --- Generate files ---
    rctx.file("BUILD.bazel", _BUILD)
    rctx.file("gcc_info.bzl", _GCC_INFO_BZL.format(
        version = version,
        target = target,
        mingw_root = mingw_root,
        tool_paths = "\n".join(tool_lines),
        include_dirs = "\n".join(include_lines),
    ))

gcc_toolchain_repo = repository_rule(
    implementation = _gcc_toolchain_repo_impl,
    attrs = {
        "gcc_path": attr.string(
            doc = "Absolute path to gcc.exe. Highest priority.",
            default = "",
        ),
        "mingw_root": attr.string(
            doc = "MinGW root directory (e.g. D:/env/msys2/mingw64). " +
                  "GCC is expected at <mingw_root>/bin/gcc.exe.",
            default = "",
        ),
    },
    environ = ["PATH", "BAZEL_SH"],
    local = True,
    doc = "Auto-detects a MinGW/MSYS2 GCC installation and exports toolchain info.",
)
