if(Boost_FOUND)
    aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR} SOURCES)
    foreach(SOURCE ${SOURCES})
        get_filename_component(TARGET ${SOURCE} NAME_WE)
        add_executable(${TARGET} ${SOURCE})
        target_include_directories(${TARGET} PRIVATE ${INCLUDE_DIR})
        target_link_libraries(${TARGET} Boost::system)
        if(WIN32)
            target_link_libraries(${TARGET} ws2_32 mswsock)
        endif()
    endforeach()
endif()
