# set(LIBS_ROOT_PATH "D:/env/libs" CACHE PATH "Additional path to search for external libraries")

# set(CMAKE_PREFIX_PATH "${LIBS_ROOT_PATH};${CMAKE_PREFIX_PATH}")

# find_package(GTest)
# find_package(benchmark)
# find_package(spdlog)
# find_package(Boost COMPONENTS system)
# find_package(OpenCV)
# # find_package(rclcpp)
# find_package(Protobuf)

local_find_package(GTest)
local_find_package(benchmark)
local_find_package(spdlog)
local_find_package(Boost COMPONENTS system)
local_find_package(OpenCV)
local_find_package(Protobuf)
local_find_package(TBB)
local_find_package(CURL)
local_find_package(nlohmann_json)
local_find_package(tl-expected)
local_find_package(cpptrace)

fetch_git_package(dbg_macro https://github.com/sharkdp/dbg-macro.git)
fetch_git_package(nlohmann_json https://github.com/nlohmann/json.git v3.11.3)
# fetch_git_package(fmt https://github.com/fmtlib/fmt.git 10.2.1)
# fetch_git_package(tomlplusplus https://github.com/marzer/tomlplusplus.git v3.4.0)
# fetch_git_package(magic_enum https://github.com/Neargye/magic_enum.git v0.9.5)
